#ifndef COMPILER_SYNTAX_ERROR_HPP
#define COMPILER_SYNTAX_ERROR_HPP

enum class syntax_error {
	NAME_FIRST_EXPECTED,
	EQUALS_SECOND_EXPECTED,
	NO_DOUBLE_EQUALS_EXPECTED,
	CLOSING_VALUE_OR_NAME_EXPECTED,
	NO_CONSECUTIVE_NUMBER_OR_NAME_EXPECTED,
	NO_CONSECUTIVE_OPERATORS_EXPECTED,
	CHARACTER_OUTSIDE_CHARACTER_SET
};

#endif
